import Link from "next/link"
import { notFound } from "next/navigation"

import { DTCCLogo } from "@/components/ui/DTCCLogo"
import { RiskBadge } from "@/components/ui/RiskBadge"
import { ariaApi } from "@/lib/api"
import type { Finding } from "@/lib/types"

import { DeleteFindingButton } from "./DeleteFindingButton"

export const dynamic = "force-dynamic"

type FindingDetailPageProps = {
  params: {
    id: string
  }
}

const borderToneByRisk: Record<string, string> = {
  HIGH: "border-[#f87171]",
  MEDIUM: "border-[#fcd34d]",
  LOW: "border-[#4bb875]",
}

const sections: Array<{
  key: keyof Pick<Finding, "criteria" | "condition" | "cause" | "consequence" | "corrective_action">
  label: string
  description: string
}> = [
  {
    key: "criteria",
    label: "CRITERIA",
    description: "What the standard requires",
  },
  {
    key: "condition",
    label: "CONDITION",
    description: "What was observed",
  },
  {
    key: "cause",
    label: "CAUSE",
    description: "Why the gap exists",
  },
  {
    key: "consequence",
    label: "CONSEQUENCE",
    description: "Business and regulatory impact",
  },
  {
    key: "corrective_action",
    label: "CORRECTIVE ACTION",
    description: "Remediation steps",
  },
]

async function getFinding(id: string) {
  try {
    return await ariaApi.getFinding(id)
  } catch (error) {
    if (error instanceof Error && error.message.includes("404")) {
      notFound()
    }
    throw error
  }
}

export default async function FindingDetailPage({ params }: FindingDetailPageProps) {
  const finding = await getFinding(params.id)
  const borderTone = borderToneByRisk[finding.risk_level] ?? "border-[#4b5563]"

  return (
    <div className="relative min-h-[calc(100vh-56px)] bg-[#0a0f0a] px-6 py-8 text-white">
      <div className="pointer-events-none absolute left-6 top-8 hidden xl:block">
        <DTCCLogo className="h-7 w-auto opacity-70" />
      </div>
      <div className="mx-auto max-w-5xl">
        <Link
          href="/findings"
          className="inline-flex items-center gap-2 text-sm text-[#8aa08e] transition-colors hover:text-[#4bb875]"
        >
          <span aria-hidden="true">←</span>
          All Findings
        </Link>

        <div className="mt-6 rounded-3xl border border-[#1a2e1a] bg-[#0f1a0f] p-6 md:p-8">
          <div className="flex flex-col gap-4 border-b border-[#1a2e1a] pb-6">
            <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
              <div className="flex items-center gap-4">
                <RiskBadge
                  level={finding.risk_level}
                  size="md"
                />
                <h1 className="text-3xl font-semibold text-white md:text-4xl">
                  {finding.title}
                </h1>
              </div>
            </div>
            <p className="text-sm text-[#8aa08e]">
              Generated by {finding.created_by} ·{" "}
              {new Date(finding.created_at).toLocaleString()}
            </p>
          </div>

          <div className="mt-8 grid gap-5">
            {sections.map((section) => (
              <section
                key={section.key}
                className={`rounded-2xl border border-[#1a2e1a] bg-[#0b140b] p-5 md:p-6`}
              >
                <div className={`border-l-4 ${borderTone} pl-4`}>
                  <div className="font-mono text-xs tracking-[0.28em] text-[#4bb875]">
                    {section.label}
                  </div>
                  <div className="mt-1 text-xs uppercase tracking-[0.16em] text-[#6f8373]">
                    {section.description}
                  </div>
                  <p className="mt-4 text-lg leading-8 text-white/95">
                    {finding[section.key]}
                  </p>
                </div>
              </section>
            ))}
          </div>

          <div className="mt-8 flex flex-col gap-4 border-t border-[#1a2e1a] pt-6 md:flex-row md:items-center md:justify-between">
            <DeleteFindingButton findingId={finding.id} />
            <button
              type="button"
              className="rounded-xl border border-[#1a2e1a] px-4 py-2.5 text-sm text-[#8aa08e] transition-colors hover:border-[#4bb875]/50 hover:text-white"
            >
              Export as PDF
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
